ColegioST/Models/Docente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ColegioST.Models
{
    public class Docente
    {
        public int DocenteId { get; set; }

        [Required(ErrorMessage = "Debes ingresar un {0}")]
        [StringLength(30, ErrorMessage =
            "El campo {0} debe contener maximo {1} y minimo {2} caracteres",
            MinimumLength = 2)]
        [Display(Name = "Nombre")]
        [RegularExpression(@"^([a-zA-Z \.\&\'\-]+)$", ErrorMessage = "Nombre invalido")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Debes ingresar un {0}")]
        [StringLength(30, ErrorMessage =
            "El campo {0} debe contener maximo {1} y minimo {2} caracteres",
            MinimumLength = 2)]
        [Display(Name = "Apellido")]
        [RegularExpression(@"^([a-zA-Z \.\&\'\-]+)$", ErrorMessage = "Nombre invalido")]
        public string Apellido { get; set; }

        [RegularExpression(@"^[0-9]{8}$", ErrorMessage = "DNI invalido")]
        public string Dni { get; set; }

        [Required(ErrorMessage = "Debes ingresar un {0}")]
        [StringLength(30, ErrorMessage =
            "El campo {0} debe contener maximo {1} y minimo {2} caracteres",
            MinimumLength = 2)]
        [Display(Name = "Especialidad")]
        [RegularExpression(@"^([a-zA-Z \.\&\'\-]+)$", ErrorMessage = "Nombre invalido")]
        public string Especialidad { get; set; }
        public bool Estado { get; set; }

        //[RegularExpression(@"^\d{4}\-(0?[1-9]|1[012])\-(0?[1-9]|[12][0-9]|3[01])$", ErrorMessage = "Fecha de nacimiento invalida")]
        public DateTime FechaNac { get; set; }

        [Required(ErrorMessage = "Debes ingresar un {0}")]
        [StringLength(15, ErrorMessage =
            "El campo {0} debe contener maximo {1} y minimo {2} caracteres",
            MinimumLength = 7)]
        [Display(Name = "Nombre de User")]
        [RegularExpression(@"^([a-zA-Z0-9 \.\&\'\-]+)$", ErrorMessage = "Nombre de User invalido")]
        public string User { get; set; }

        [Required(ErrorMessage = "Debes ingresar un {0}")]
        [StringLength(15, ErrorMessage =
            "El campo {0} debe contener maximo {1} y minimo {2} caracteres",
            MinimumLength = 7)]
        [Display(Name = "Nombre de User")]
        [RegularExpression(@"^([a-zA-Z0-9 \.\&\'\-]+)$", ErrorMessage = "Password invalido")]
        public string Password { get; set; }


        //
        public ICollection<Curso> Curso { get; set; }

    }
}

ColegioST/Controllers/DocenteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ColegioST.Models;

namespace ColegioST.Controllers
{
    public class DocenteController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Docente
        public ActionResult Index()
        {
            return View(db.Docentes.ToList());
        }

        // GET: Docente/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Docente docente = db.Docentes.Find(id);
            if (docente == null)
            {
                return HttpNotFound();
            }
            return View(docente);
        }

        // GET: Docente/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Docente/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DocenteId,Nombre,Apellido,Dni,Especialidad,Estado,FechaNac,User,Password")] Docente docente)
        {
            if (ModelState.IsValid)
            {
                db.Docentes.Add(docente);
                db.SaveChanges();
                TempData["UpdateSuccess"] = "Se Guardo Correctamente";
                return RedirectToAction("Index");
            }

            return View(docente);
        }

        // GET: Docente/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Docente docente = db.Docentes.Find(id);
            if (docente == null)
            {
                return HttpNotFound();
            }
            return View(docente);
        }

        // POST: Docente/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DocenteId,Nombre,Apellido,Dni,Especialidad,Estado,FechaNac,User,Password")] Docente docente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(docente).State = EntityState.Modified;
                db.SaveChanges();
                TempData["UpdateSuccess"] = "Se Actualizo Correctamente";
                return RedirectToAction("Index");
            }
            return View(docente);
        }

        // GET: Docente/Delete/5
        public ActionResult Delete(int? id)
        {
            Docente docente = db.Docentes.Find(id);
            db.Docentes.Remove(docente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Docente/Delete/5
        /*
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Docente docente = db.Docentes.Find(id);
            db.Docentes.Remove(docente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }*/
    }
}

ColegioST/Views/Docente/Create.cshtml
@model ColegioST.Models.Docente


<nav class="navbar navbar-default" id="nav">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span><span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a id="A1" class="navbar-brand" href="/Home/Index">Santa Teresita App</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">


                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Curso/index">Cursos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Docente/index">Docentes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Alumno/Index">Alumnos</a>
                </li>


            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</nav>

<div class="container body-content">

    @{
        ViewBag.Title = "Create";
    }


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <center><h3>Registrar Docente</h3></center>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Dni, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Dni, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Dni, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Especialidad, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Especialidad, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Especialidad, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Estado)
                        @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
               <label class="control-label col-md-2"> Fecha de Nacimiento</label>
                
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FechaNac, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FechaNac, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.User, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.User, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.User, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" align='center'>
                <i class="icon-search"></i>
                <input type="submit" value="Registrar" class="btn btn-primary" />
                <a href="/Docente/Index" class="btn btn-primary">Cancelar</a>
            </div>
        </div>
    }


    <hr />
    <footer>
        <p style="text-align: center">&copy; @DateTime.Now.Year - Santa Teresita App</p>
    </footer>
</div>


    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

<style>
    .checkbox {
        margin-left: 20px;
    }
</style>

ColegioST/Views/Docente/Delete.cshtml
@model ColegioST.Models.Docente

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Docente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dni)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dni)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Especialidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Especialidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNac)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNac)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ColegioST/Views/Docente/Details.cshtml
@model ColegioST.Models.Docente


<nav class="navbar navbar-default" id="nav">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span><span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a id="A1" class="navbar-brand" href="/Home/Index">Santa Teresita App</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">


                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Curso/index">Cursos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Docente/index">Docentes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Alumno/Index">Alumnos</a>
                </li>


            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</nav>

<div class="container body-content">

    @{
        ViewBag.Title = "Details";
    }

    <div style="text-align:center">
        <h2>Información del Docente</h2>
    </div>

    <div>

        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nombre)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Apellido)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Apellido)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Dni)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Dni)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Especialidad)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Especialidad)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Estado)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Estado)
            </dd>

            <dt>
                Fecha de Nacimiento
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FechaNac)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.User)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.User)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Password)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Password)
            </dd>

        </dl>
    </div>

    <div style="text-align:center">
        <a href="@Url.Action("Edit", "Docente")" class="btn btn-primary">
            Editar

        </a>
        <a href="@Url.Action("Index", "Docente")" class="btn btn-primary">
            Regresar

        </a>
    </div>

    <hr />
    <footer>
        <p style="text-align: center">&copy; @DateTime.Now.Year - Santa Teresita App</p>
    </footer>
</div>

ColegioST/Views/Docente/Edit.cshtml
@model ColegioST.Models.Docente


<nav class="navbar navbar-default" id="nav">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span><span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a id="A1" class="navbar-brand" href="/Home/Index">Santa Teresita App</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">


                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Curso/index">Cursos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Docente/index">Docentes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Alumno/Index">Alumnos</a>
                </li>


            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</nav>

<div class="container body-content">

    @{
        ViewBag.Title = "Edit";
    }

    <div style="text-align:center">
        <h4>Editar Información del Docente</h4>
    </div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.DocenteId)

            <div class="form-group">
                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Dni, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Dni, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Dni, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Especialidad, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Especialidad, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Especialidad, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Estado)
                        @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FechaNac, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FechaNac, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FechaNac, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.User, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.User, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.User, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" align='center'>
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Regresar", "Index")
    </div>


    <hr />
    <footer>
        <p style="text-align: center">&copy; @DateTime.Now.Year - Santa Teresita App</p>
    </footer>
</div>




    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

<style>
    .checkbox {
        margin-left: 20px;
    }
</style>

ColegioST/Views/Docente/Index.cshtml
@model IEnumerable<ColegioST.Models.Docente>


<nav class="navbar navbar-default" id="nav">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span><span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a id="A1" class="navbar-brand" href="/Home/Index">Santa Teresita App</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">


                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Curso/index">Cursos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Docente/index">Docentes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Alumno/Index">Alumnos</a>
                </li>
               

            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</nav>

<div class="container body-content">
    @{
        ViewBag.Title = "Index";
    }

    @if (TempData["UpdateSuccess"] != null)
    {
        <div class="alert alert-success">@TempData["UpdateSuccess"]</div>
    }

    <center><h2>Docentes Registrados</h2></center>
    <hr />
    <p>
        <div style="text-align:right">
            <a href="@Url.Action("Create", "Docente")" class="btn btn-primary">
                Registrar Nuevo Docente
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </a>
        </div>
    </p>


    <div class="table-responsive">
        <table class="table table-striped">
            
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Apellido)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Dni)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Especialidad)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Estado)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FechaNac)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.User)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Password)
                    </th>
                    <th></th>
                </tr>
            
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Apellido)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dni)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Especialidad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Estado)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FechaNac)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.User)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Password)
                    </td>
                    <td>
                        <a href="/docente/edit/@item.DocenteId">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </a> |
                        <a href="/docente/details/@item.DocenteId">
                            <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
                        </a> |

                        <a id="deleteItem" class="deleteItem" data-target="#basic" data-toggle="modal" data-path="@Url.Action("Delete", "Docente", new { id = @item.DocenteId })">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </a>

                        <div class="modal fade" id="basic" tabindex="-1" role="basic" aria-hidden="true" style="display: none;">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                        <h4 class="modal-title">Confirmar Eliminación</h4>
                                    </div>
                                    <div class="modal-body">
                                        Desea elimina este registro ?
                                    </div>
                                    <div class="modal-footer">
                                        <button data-dismiss="modal" type="button" class="btn btn-default">Cancelar</button>
                                        <button id="btnContinueDelete" type="button" class="btn btn-primary">Eliminar</button>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </td>
                </tr>


            }


        </table>
        
    </div>


    <hr />
    <footer>
        <p style="text-align: center">&copy; @DateTime.Now.Year - Santa Teresita App</p>
    </footer>
</div>


<script>
    // $("div").empty();

    $(function () {
        $(".modal-link").click(function (event) {
            event.preventDefault()
            $('#myModal').removeData("modal")
            $('#myModal').modal({ remote: $(this).attr("href") })
        })
    })


    var path_to_delete;

    $(".deleteItem").click(function (e) {
        path_to_delete = $(this).data('path');
    });
    $('#btnContinueDelete').click(function () {
        window.location = path_to_delete;
    });

    $(".alert").delay(4000).slideUp(200, function () {
        $(this).alert('close');
    });

    $(".alert-dismissible").fadeTo(2000, 500).slideUp(500, function () {
        $(".alert-dismissible").alert('close');
    });
</script>