ColegioST/Models/Curso.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ColegioST.Models
{
    public class Curso
    {
        public int CursoId { get; set; }

        [Required(ErrorMessage = "Debes ingresar un {0}")]
        [StringLength(30, ErrorMessage =
            "El campo {0} debe contener maximo {1} y minimo {2} caracteres",
            MinimumLength = 2)]
        [Display(Name = "Nombre")]
        [RegularExpression(@"^([a-zA-Z \.\&\'\-]+)$", ErrorMessage = "Nombre invalido")]
        public string Nombre { get; set; }
        public string Grado { get; set; }
        public string Seccion { get; set; }
        public bool Estado { get; set; }

        //fk dcocente
        public int DocenteId { get; set; }
        public Docente Docente { get; set; }

        //muchos a muchos
        public virtual ICollection<AlumnoCurso> AlumnoCurso { get; set; }
    }
}

ColegioST/Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ColegioST.Models;

namespace ColegioST.Controllers
{
    public class CursoController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Curso
        public ActionResult Index()
        {
            var cursoes = db.Cursoes.Include(c => c.Docente);
            return View(cursoes.ToList());
        }

        // GET: Curso/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = db.Cursoes.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            return View(curso);
        }

        // GET: Curso/Create
        public ActionResult Create()
        {
            ViewBag.DocenteId = new SelectList(db.Docentes, "DocenteId", "Nombre");
            return View();
        }

        // POST: Curso/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CursoId,Nombre,Grado,Seccion,Estado,DocenteId")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                db.Cursoes.Add(curso);
                db.SaveChanges();
                TempData["UpdateSuccess"] = "Se Guardo Correctamente";
                return RedirectToAction("Index");
            }

            ViewBag.DocenteId = new SelectList(db.Docentes, "DocenteId", "Nombre", curso.DocenteId);
            return View(curso);
        }

        // GET: Curso/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = db.Cursoes.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            ViewBag.DocenteId = new SelectList(db.Docentes, "DocenteId", "Nombre", curso.DocenteId);
            return View(curso);
        }

        // POST: Curso/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CursoId,Nombre,Grado,Seccion,Estado,DocenteId")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                db.Entry(curso).State = EntityState.Modified;
                db.SaveChanges();
                TempData["UpdateSuccess"] = "Se Actualizo Correctamente";
                return RedirectToAction("Index");
            }
            ViewBag.DocenteId = new SelectList(db.Docentes, "DocenteId", "Nombre", curso.DocenteId);
            return View(curso);
        }

        // GET: Curso/Delete/5
        public ActionResult Delete(int? id)
        {
            Curso curso = db.Cursoes.Find(id);
            db.Cursoes.Remove(curso);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Curso/Delete/5
       /* [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Curso curso = db.Cursoes.Find(id);
            db.Cursoes.Remove(curso);
            db.SaveChanges();
            return RedirectToAction("Index");
        }*/

            /*
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        */
    }
}

ColegioST/Views/Curso/Create.cshtml
@model ColegioST.Models.Curso



<nav class="navbar navbar-default" id="nav">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span><span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a id="A1" class="navbar-brand" href="/Home/Index">Santa Teresita App</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">


                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Curso/index">Cursos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Docente/index">Docentes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Alumno/Index">Alumnos</a>
                </li>


            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</nav>

<div class="container body-content">

    @{
        ViewBag.Title = "Create";
    }


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <center><h3>Registrar Curso</h3></center>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Grado, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.Grado, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.DropDownList("Grado", new List<SelectListItem>

                 {
                    new SelectListItem{ Text="1°", Value = "1" },
                    new SelectListItem{ Text="2°", Value = "2" },
                    new SelectListItem{ Text="3°", Value = "3" },
                    new SelectListItem{ Text="4°", Value = "4" },
                    new SelectListItem{ Text="5°", Value = "5" }
                    
                 }, new { @class = "form-control" })

                    @Html.ValidationMessageFor(model => model.Grado, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Seccion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.Seccion, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.DropDownList("Seccion", new List<SelectListItem>

                 {
                    new SelectListItem{ Text="A", Value = "A" },
                    new SelectListItem{ Text="B", Value = "B" },
                    new SelectListItem{ Text="C", Value = "C" },
                    new SelectListItem{ Text="D", Value = "D" }
                 }, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Seccion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Estado)
                        @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DocenteId, "DocenteId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("DocenteId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DocenteId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" align='center'>
                <i class="icon-search"></i>
                <input type="submit" value="Registrar" class="btn btn-primary" />
                <a href="/Curso/Index" class="btn btn-primary">Cancelar</a>
            </div>
        </div>
    }

    <hr />
    <footer>
        <p style="text-align: center">&copy; @DateTime.Now.Year - Santa Teresita App</p>
    </footer>
</div>


</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<style>
    .checkbox {
        margin-left: 20px;
    }
</style>

ColegioST/Views/Curso/Delete.cshtml
@model ColegioST.Models.Curso

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Curso</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Docente.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Docente.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Seccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Seccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ColegioST/Views/Curso/Details.cshtml
@model ColegioST.Models.Curso


<nav class="navbar navbar-default" id="nav">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span><span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a id="A1" class="navbar-brand" href="/Home/Index">Santa Teresita App</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">


                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Curso/index">Cursos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Docente/index">Docentes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Alumno/Index">Alumnos</a>
                </li>


            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</nav>

<div class="container body-content">

    @{
        ViewBag.Title = "Details";
    }

    <div style="text-align:center">
        <h2>Información del Curso</h2>
    </div>

    <div>

        <hr />
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayFor(model => model.Docente.Nombre)
            </dt>


            <dd>
                @Html.DisplayFor(model => model.Docente.Nombre)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nombre)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Grado)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Grado)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Seccion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Seccion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Estado)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Estado)
            </dd>

        </dl>
    </div>

    <div style="text-align:center">
        <a href="@Url.Action("Edit", "Curso")" class="btn btn-primary">
            Editar

        </a>
        <a href="@Url.Action("Index", "Curso")" class="btn btn-primary">
            Regresar

        </a>
    </div>


    <hr />
    <footer>
        <p style="text-align: center">&copy; @DateTime.Now.Year - Santa Teresita App</p>
    </footer>
</div>


</div>

ColegioST/Views/Curso/Edit.cshtml
@model ColegioST.Models.Curso



<nav class="navbar navbar-default" id="nav">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span><span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a id="A1" class="navbar-brand" href="/Home/Index">Santa Teresita App</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">


                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Curso/index">Cursos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Docente/index">Docentes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Alumno/Index">Alumnos</a>
                </li>


            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</nav>

<div class="container body-content">


    @{
        ViewBag.Title = "Edit";
    }

    <div style="text-align:center">
        <h3>Editar Información del Curso</h3>
    </div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.CursoId)

            <div class="form-group">
                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Grado, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Grado, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Grado, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2"> Sección</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Seccion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Seccion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Estado)
                        @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2"> Docente</label>
                <div class="col-md-10">
                    @Html.DropDownList("DocenteId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DocenteId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" align='center'>
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Regresar", "Index")
    </div>

    <hr />
    <footer>
        <p style="text-align: center">&copy; @DateTime.Now.Year - Santa Teresita App</p>
    </footer>
</div>


    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

<style>
    .checkbox {
        margin-left: 20px;
    }
</style>

ColegioST/Views/Curso/Index.cshtml
@model IEnumerable<ColegioST.Models.Curso>

<nav class="navbar navbar-default" id="nav">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span><span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a id="A1" class="navbar-brand" href="/Home/Index">Santa Teresita App</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">


                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Curso/index">Cursos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Docente/index">Docentes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/Alumno/Index">Alumnos</a>
                </li>
                

            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</nav>

<div class="container body-content">

    @{
        ViewBag.Title = "Index";
    }

    @if (TempData["UpdateSuccess"] != null)
    {
        <div class="alert alert-success">@TempData["UpdateSuccess"]</div>
    }

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>




    <center><h2>Cursos Registrados</h2></center>
    <hr />
    <p>

        <div style="text-align:right">
            <a href="@Url.Action("Create", "Curso")" class="btn btn-primary">
                Registrar Nuevo Curso
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </a>
        </div>
    </p>


    <div class="table-responsive">
        <table class="table table-striped">
            
                <tr class="bg-secondary">
                    <th>
                        Docente
                    </th>
                    <th>
                        Curso
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Grado)
                    </th>
                    <th>
                        Sección
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Estado)
                    </th>
                    <th></th>
                </tr>
          
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Docente.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Grado)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Seccion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Estado)
                    </td>
                    <td>
                        <a href="/curso/edit/@item.CursoId">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </a> |
                        <a href="/curso/details/@item.CursoId">
                            <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
                        </a>
                        |
                        <a id="deleteItem" class="deleteItem" data-target="#basic" data-toggle="modal" data-path="@Url.Action("Delete", "Curso", new { id = @item.CursoId })">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </a>

                        <div class="modal fade" id="basic" tabindex="-1" role="basic" aria-hidden="true" style="display: none;">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                        <h4 class="modal-title">Confirmar Eliminación</h4>
                                    </div>
                                    <div class="modal-body">
                                        Desea elimina este registro ?
                                    </div>
                                    <div class="modal-footer">
                                        <button data-dismiss="modal" type="button" class="btn btn-default">Cancelar</button>
                                        <button id="btnContinueDelete" type="button" class="btn btn-primary">Eliminar</button>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </td>
                </tr>
            }

        </table>
        
    </div>

    <hr />
    <footer>
        <p style="text-align: center">&copy; @DateTime.Now.Year - Santa Teresita App</p>
    </footer>
</div>


    <script>
        // $("div").empty();

        $(function () {
            $(".modal-link").click(function (event) {
                event.preventDefault()
                $('#myModal').removeData("modal")
                $('#myModal').modal({ remote: $(this).attr("href") })
            })
        })


        var path_to_delete;

        $(".deleteItem").click(function(e) {
            path_to_delete = $(this).data('path');
        });
        $('#btnContinueDelete').click(function () {
            window.location = path_to_delete;
        });

      

        $(".alert").delay(4000).slideUp(200, function () {
            $(this).alert('close');
        });

        $(".alert-dismissible").fadeTo(2000, 500).slideUp(500, function () {
            $(".alert-dismissible").alert('close');
        });
    </script>